FROM --platform=linux/amd64 debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc \
        gcc-multilib \
        libc6-dev \
        libc6-dev-i386 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
